---

- name: Prevent packages from being upgraded
  dpkg_selections:
    name: proxmox-ve
    selection: hold

- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file

- name: Reboot the server
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true

